apiVersion: v1
kind: Secret
metadata:
  name: cat-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: |
  MYSQL_USERNAME: {{ .Values.env.mysql.username }}
   MYSQL_PASSWORD: {{ .Values.env.mysql.password }}
