apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cat.mysql.name" . }}
  labels:
    {{- include "cat.module.labels" . | nindent 4 }}
    {{- with .Values.cat.mysql.labels }}
        {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  type: {{ .Values.cat.mysql.servicetype | default "ClusterIP" }}
  ports:
    - port: {{ .Values.cat.mysql.port | default "3306" }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "cat.mysql.selectorLabels" . | nindent 4 }}
