/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.status.model;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringReader;

import com.dianping.cat.status.model.entity.StatusInfo;
import com.dianping.cat.status.model.transform.DefaultXmlBuilder;
import com.dianping.cat.status.model.transform.DefaultXmlParser;

import org.xml.sax.InputSource;

public class StatusInfoHelper {
   public static String asXml(IEntity<?> entity) {
      return new DefaultXmlBuilder().build(entity);
   }

   public static <T extends IEntity<?>> T fromXml(Class<T> entityType, InputStream in) throws IOException {
      return new DefaultXmlParser().parse(entityType, new InputSource(withoutBom(in)));
   }

   public static <T extends IEntity<?>> T fromXml(Class<T> entityType, String xml) throws IOException {
      return new DefaultXmlParser().parse(entityType, new InputSource(new StringReader(xml)));
   }

   public static StatusInfo fromXml(InputStream in) throws IOException {
      return fromXml(StatusInfo.class, in);
   }

   public static StatusInfo fromXml(String xml) throws IOException {
      return fromXml(StatusInfo.class, xml);
   }

   /**
    * removes Byte Order Mark(BOM) at the head of windows UTF-8 file.
    */
   private static InputStream withoutBom(InputStream in) throws IOException {
      if (!(in instanceof BufferedInputStream)) {
         in = new BufferedInputStream(in);
      }

      in.mark(3);

      /** UTF-8, with BOM **/
      if (in.read() != 0xEF || in.read() != 0xBB || in.read() != 0xBF) {
         in.reset();
      }

      return in;
   }
}
