/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model;

public class Constants {

   public static final String ATTR_ENABLED = "enabled";

   public static final String ATTR_HTTP_PORT = "http-port";

   public static final String ATTR_ID = "id";

   public static final String ATTR_IP = "ip";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_PORT = "port";

   public static final String ATTR_TENANT_TOKEN = "tenant-token";

   public static final String ELEMENT_VALUE = "value";

   public static final String ENTITY_CONFIG = "config";

   public static final String ENTITY_DOMAIN = "domain";

   public static final String ENTITY_HOST = "host";

   public static final String ENTITY_PROPERTY = "property";

   public static final String ENTITY_SERVER = "server";

   public static final String ENTITY_PROPERTIES = "properties";

   public static final String ENTITY_SERVERS = "servers";
}
