/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model;

import com.dianping.cat.configuration.model.entity.ClientConfig;
import com.dianping.cat.configuration.model.entity.Domain;
import com.dianping.cat.configuration.model.entity.Host;
import com.dianping.cat.configuration.model.entity.Property;
import com.dianping.cat.configuration.model.entity.Server;

public interface IVisitor {

   public void visitConfig(ClientConfig config);

   public void visitDomain(Domain domain);

   public void visitHost(Host host);

   public void visitProperty(Property property);

   public void visitServer(Server server);
}
