/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model.entity;

import com.dianping.cat.configuration.model.BaseEntity;
import com.dianping.cat.configuration.model.IVisitor;

public class Host extends BaseEntity<Host> {
   private String m_name;

   private String m_ip;

   private Integer m_id;

   private boolean m_enabled = true;

   public Host() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitHost(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof Host) {
         Host _o = (Host) obj;

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         if (!equals(getIp(), _o.getIp())) {
            return false;
         }

         if (!equals(getId(), _o.getId())) {
            return false;
         }

         if (getEnabled() != _o.getEnabled()) {
            return false;
         }


         return true;
      }

      return false;
   }

   public boolean getEnabled() {
      return m_enabled;
   }

   public Integer getId() {
      return m_id;
   }

   public String getIp() {
      return m_ip;
   }

   public String getName() {
      return m_name;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());
      hash = hash * 31 + (m_ip == null ? 0 : m_ip.hashCode());
      hash = hash * 31 + (m_id == null ? 0 : m_id.hashCode());
      hash = hash * 31 + (m_enabled ? 1 : 0);

      return hash;
   }

   public boolean isEnabled() {
      return m_enabled;
   }

   @Override
   public void mergeAttributes(Host other) {
      if (other.getName() != null) {
         m_name = other.getName();
      }

      if (other.getIp() != null) {
         m_ip = other.getIp();
      }

      if (other.getId() != null) {
         m_id = other.getId();
      }

      m_enabled = other.getEnabled();
   }

   public Host setEnabled(boolean enabled) {
      m_enabled = enabled;
      return this;
   }

   public Host setId(Integer id) {
      m_id = id;
      return this;
   }

   public Host setIp(String ip) {
      m_ip = ip;
      return this;
   }

   public Host setName(String name) {
      m_name = name;
      return this;
   }

}
