/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model.transform;

import static com.dianping.cat.configuration.model.Constants.ATTR_ENABLED;
import static com.dianping.cat.configuration.model.Constants.ATTR_HTTP_PORT;
import static com.dianping.cat.configuration.model.Constants.ATTR_ID;
import static com.dianping.cat.configuration.model.Constants.ATTR_IP;
import static com.dianping.cat.configuration.model.Constants.ATTR_NAME;
import static com.dianping.cat.configuration.model.Constants.ATTR_PORT;
import static com.dianping.cat.configuration.model.Constants.ATTR_TENANT_TOKEN;

import java.util.Map;
import org.xml.sax.Attributes;

import com.dianping.cat.configuration.model.entity.ClientConfig;
import com.dianping.cat.configuration.model.entity.Domain;
import com.dianping.cat.configuration.model.entity.Host;
import com.dianping.cat.configuration.model.entity.Property;
import com.dianping.cat.configuration.model.entity.Server;

public class DefaultXmlMaker {

   public ClientConfig buildConfig(Attributes attributes) {
      String enabled = attributes.getValue(ATTR_ENABLED);
      ClientConfig config = new ClientConfig();

      if (enabled != null) {
         config.setEnabled(convert(Boolean.class, enabled, false));
      }

      Map<String, String> dynamicAttributes = config.getDynamicAttributes();
      int _length = attributes == null ? 0 : attributes.getLength();

      for (int i = 0; i < _length; i++) {
         String _name = attributes.getQName(i);
         String _value = attributes.getValue(i);

         dynamicAttributes.put(_name, _value);
      }

      dynamicAttributes.remove(ATTR_ENABLED);

      return config;
   }

   public Domain buildDomain(Attributes attributes) {
      String name = attributes.getValue(ATTR_NAME);
      String id = attributes.getValue(ATTR_ID);
      String tenantToken = attributes.getValue(ATTR_TENANT_TOKEN);
      String enabled = attributes.getValue(ATTR_ENABLED);
      Domain domain = new Domain();

      if (name != null) {
         domain.setName(name);
      }

      if (id != null) {
         domain.setId(convert(Integer.class, id, null));
      }

      if (tenantToken != null) {
         domain.setTenantToken(tenantToken);
      }

      if (enabled != null) {
         domain.setEnabled(convert(Boolean.class, enabled, false));
      }

      Map<String, String> dynamicAttributes = domain.getDynamicAttributes();
      int _length = attributes == null ? 0 : attributes.getLength();

      for (int i = 0; i < _length; i++) {
         String _name = attributes.getQName(i);
         String _value = attributes.getValue(i);

         dynamicAttributes.put(_name, _value);
      }

      dynamicAttributes.remove(ATTR_NAME);
      dynamicAttributes.remove(ATTR_ID);
      dynamicAttributes.remove(ATTR_TENANT_TOKEN);
      dynamicAttributes.remove(ATTR_ENABLED);

      return domain;
   }

   public Host buildHost(Attributes attributes) {
      String name = attributes.getValue(ATTR_NAME);
      String ip = attributes.getValue(ATTR_IP);
      String id = attributes.getValue(ATTR_ID);
      String enabled = attributes.getValue(ATTR_ENABLED);
      Host host = new Host();

      if (name != null) {
         host.setName(name);
      }

      if (ip != null) {
         host.setIp(ip);
      }

      if (id != null) {
         host.setId(convert(Integer.class, id, null));
      }

      if (enabled != null) {
         host.setEnabled(convert(Boolean.class, enabled, false));
      }

      return host;
   }

   public Property buildProperty(Attributes attributes) {
      String name = attributes.getValue(ATTR_NAME);
      Property property = new Property(name);

      return property;
   }

   public Server buildServer(Attributes attributes) {
      String ip = attributes.getValue(ATTR_IP);
      String port = attributes.getValue(ATTR_PORT);
      String httpPort = attributes.getValue(ATTR_HTTP_PORT);
      String enabled = attributes.getValue(ATTR_ENABLED);
      Server server = new Server(ip);

      if (port != null) {
         server.setPort(convert(Integer.class, port, 0));
      }

      if (httpPort != null) {
         server.setHttpPort(convert(Integer.class, httpPort, 0));
      }

      if (enabled != null) {
         server.setEnabled(convert(Boolean.class, enabled, false));
      }

      return server;
   }

   @SuppressWarnings("unchecked")
   protected <T> T convert(Class<T> type, String value, T defaultValue) {
      if (value == null || value.length() == 0) {
         return defaultValue;
      }

      if (type == Boolean.class || type == Boolean.TYPE) {
         return (T) Boolean.valueOf(value);
      } else if (type == Integer.class || type == Integer.TYPE) {
         return (T) Integer.valueOf(value);
      } else if (type == Long.class || type == Long.TYPE) {
         return (T) Long.valueOf(value);
      } else if (type == Short.class || type == Short.TYPE) {
         return (T) Short.valueOf(value);
      } else if (type == Float.class || type == Float.TYPE) {
         return (T) Float.valueOf(value);
      } else if (type == Double.class || type == Double.TYPE) {
         return (T) Double.valueOf(value);
      } else if (type == Byte.class || type == Byte.TYPE) {
         return (T) Byte.valueOf(value);
      } else if (type == Character.class || type == Character.TYPE) {
         return (T) (Character) value.charAt(0);
      } else {
         return (T) value;
      }
   }
}
