/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model.transform;

import static com.dianping.cat.configuration.model.Constants.ATTR_ENABLED;
import static com.dianping.cat.configuration.model.Constants.ATTR_HTTP_PORT;
import static com.dianping.cat.configuration.model.Constants.ATTR_ID;
import static com.dianping.cat.configuration.model.Constants.ATTR_IP;
import static com.dianping.cat.configuration.model.Constants.ATTR_NAME;
import static com.dianping.cat.configuration.model.Constants.ATTR_PORT;
import static com.dianping.cat.configuration.model.Constants.ATTR_TENANT_TOKEN;
import static com.dianping.cat.configuration.model.Constants.ENTITY_CONFIG;
import static com.dianping.cat.configuration.model.Constants.ENTITY_DOMAIN;
import static com.dianping.cat.configuration.model.Constants.ENTITY_HOST;
import static com.dianping.cat.configuration.model.Constants.ENTITY_PROPERTIES;
import static com.dianping.cat.configuration.model.Constants.ENTITY_PROPERTY;
import static com.dianping.cat.configuration.model.Constants.ENTITY_SERVER;
import static com.dianping.cat.configuration.model.Constants.ENTITY_SERVERS;

import java.lang.reflect.Array;
import java.util.Collection;

import com.dianping.cat.configuration.model.IEntity;
import com.dianping.cat.configuration.model.IVisitor;
import com.dianping.cat.configuration.model.entity.ClientConfig;
import com.dianping.cat.configuration.model.entity.Domain;
import com.dianping.cat.configuration.model.entity.Host;
import com.dianping.cat.configuration.model.entity.Property;
import com.dianping.cat.configuration.model.entity.Server;

public class DefaultXmlBuilder implements IVisitor {

   private IVisitor m_visitor = this;

   private int m_level;

   private StringBuilder m_sb;

   private boolean m_compact;

   public DefaultXmlBuilder() {
      this(false);
   }

   public DefaultXmlBuilder(boolean compact) {
      m_compact = compact;
   }

   public String build(IEntity<?> entity) {
      m_sb = new StringBuilder(8192);
      m_sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");

      entity.accept(m_visitor);
      return m_sb.toString();
   }

   protected void endTag(String name) {
      m_level--;

      indent();
      m_sb.append("</").append(name).append(">\r\n");
   }

   protected String escape(Object value) {
      return escape(value, false);
   }
   
   protected String escape(Object value, boolean text) {
      if (value == null) {
         return null;
      }

      String str = toString(value);
      int len = str.length();
      StringBuilder sb = new StringBuilder(len + 16);

      for (int i = 0; i < len; i++) {
         final char ch = str.charAt(i);

         switch (ch) {
         case '<':
            sb.append("&lt;");
            break;
         case '>':
            sb.append("&gt;");
            break;
         case '&':
            sb.append("&amp;");
            break;
         case '"':
            if (!text) {
               sb.append("&quot;");
               break;
            }
         default:
            sb.append(ch);
            break;
         }
      }

      return sb.toString();
   }
   
   protected void indent() {
      if (!m_compact) {
         for (int i = m_level - 1; i >= 0; i--) {
            m_sb.append("   ");
         }
      }
   }

   protected void startTag(String name) {
      startTag(name, false, null);
   }
   
   protected void startTag(String name, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, closed, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, false, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, Object text, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      indent();

      m_sb.append('<').append(name);

      int len = nameValues.length;

      for (int i = 0; i + 1 < len; i += 2) {
         Object attrName = nameValues[i];
         Object attrValue = nameValues[i + 1];

         if (attrValue != null) {
            m_sb.append(' ').append(attrName).append("=\"").append(escape(attrValue)).append('"');
         }
      }

      if (dynamicAttributes != null) {
         for (java.util.Map.Entry<String, String> e : dynamicAttributes.entrySet()) {
            m_sb.append(' ').append(e.getKey()).append("=\"").append(escape(e.getValue())).append('"');
         }
      }

      if (text != null && closed) {
         m_sb.append('>');
         m_sb.append(escape(text, true));
         m_sb.append("</").append(name).append(">\r\n");
      } else {
         if (closed) {
            m_sb.append('/');
         } else {
            m_level++;
         }
   
         m_sb.append(">\r\n");
      }
   }

   @SuppressWarnings("unchecked")
   protected String toString(Object value) {
      if (value instanceof String) {
         return (String) value;
      } else if (value instanceof Collection) {
         Collection<Object> list = (Collection<Object>) value;
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (Object item : list) {
            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }

         return sb.toString();
      } else if (value.getClass().isArray()) {
         int len = Array.getLength(value);
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (int i = 0; i < len; i++) {
            Object item = Array.get(value, i);

            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }
		
         return sb.toString();
      }
 
      return String.valueOf(value);
   }

   @Override
   public void visitConfig(ClientConfig config) {
      startTag(ENTITY_CONFIG, config.getDynamicAttributes(), ATTR_ENABLED, config.isEnabled());

      if (config.getHost() != null) {
         config.getHost().accept(m_visitor);
      }

      if (config.getDomain() != null) {
         config.getDomain().accept(m_visitor);
      }

      if (!config.getServers().isEmpty()) {
         startTag(ENTITY_SERVERS);

         for (Server server : config.getServers()) {
            server.accept(m_visitor);
         }

         endTag(ENTITY_SERVERS);
      }

      if (!config.getProperties().isEmpty()) {
         startTag(ENTITY_PROPERTIES);

         for (Property property : config.getProperties().values()) {
            property.accept(m_visitor);
         }

         endTag(ENTITY_PROPERTIES);
      }

      endTag(ENTITY_CONFIG);
   }

   @Override
   public void visitDomain(Domain domain) {
      startTag(ENTITY_DOMAIN, true, domain.getDynamicAttributes(), ATTR_NAME, domain.getName(), ATTR_ID, domain.getId(), ATTR_TENANT_TOKEN, domain.getTenantToken(), ATTR_ENABLED, domain.isEnabled());
   }

   @Override
   public void visitHost(Host host) {
      startTag(ENTITY_HOST, true, null, ATTR_NAME, host.getName(), ATTR_IP, host.getIp(), ATTR_ID, host.getId(), ATTR_ENABLED, host.isEnabled());
   }

   @Override
   public void visitProperty(Property property) {
      startTag(ENTITY_PROPERTY, property.getValue(), true, null, ATTR_NAME, property.getName());
   }

   @Override
   public void visitServer(Server server) {
      startTag(ENTITY_SERVER, true, null, ATTR_IP, server.getIp(), ATTR_PORT, server.getPort(), ATTR_HTTP_PORT, server.getHttpPort(), ATTR_ENABLED, server.isEnabled());
   }
}
