/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package com.dianping.cat.configuration.model.transform;

import java.util.ArrayList;
import java.util.List;

import com.dianping.cat.configuration.model.entity.ClientConfig;
import com.dianping.cat.configuration.model.entity.Domain;
import com.dianping.cat.configuration.model.entity.Host;
import com.dianping.cat.configuration.model.entity.Property;
import com.dianping.cat.configuration.model.entity.Server;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onDomain(final ClientConfig parent, final Domain domain) {
      parent.setDomain(domain);
      return true;
   }

   public boolean onHost(final ClientConfig parent, final Host host) {
      parent.setHost(host);
      return true;
   }

   public boolean onProperty(final ClientConfig parent, final Property property) {
      parent.addProperty(property);
      return true;
   }

   public boolean onServer(final ClientConfig parent, final Server server) {
      parent.addServer(server);
      return true;
   }
}
