name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  push:
    branches:
      - feature/workflow-docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: docker buildx create --use --name cat-bulder --driver docker-container &&
           docker buildx --platform linux/arm,linux/arm64,linux/amd64 --load
            -t $(HUB)/$(NAME):$(TAG) -t $(HUB)/$(NAME):latest
            -f docker/Dockerfile . &&
            docker buildx rm skywalking_main
